services:
  bifrost:
    build: ./web
    container_name: bifrost
    ports:
      - 443:443
    networks:
      - yggdrasil
    develop:
      watch:
        - action: rebuild
          path: ./web/package-lock.json
        - action: sync+restart
          path: ./web/nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
        - action: sync
          path: ./web/dist
          target: /web/static
  mimir:
    build: .
    container_name: mimir
    restart: always
    environment:
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - CONTACT_PHONE=${CONTACT_PHONE}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - DEPARTMENT_NAME=${DEPARTMENT_NAME}
      - DEPARTMENT_URL=${DEPARTMENT_URL}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_PHASE=${SERVICE_PHASE}
      - SERVICE_URL=${SERVICE_URL}
    expose:
      - 5000
    networks:
      - yggdrasil
    depends_on:
      - bifrost
      - loki
      - mimisbrunnr
    develop:
      watch:
        - action: rebuild
          path: ./requirements.txt
          target: /home/appuser/requirements.txt
        - action: sync+restart
          path: ./app
          target: /home/appuser/app
  loki:
    image: redis:7-alpine
    container_name: loki
    restart: always
    expose:
      - 6379
    networks:
      - yggdrasil
    volumes:
      - redis_data:/data
  mimisbrunnr:
    image: postgres:17-alpine
    container_name: mimisbrunnr
    restart: always
    expose:
      - 5432
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - yggdrasil
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  yggdrasil:

volumes:
  redis_data:
  pg_data:
