"""add location to person

Revision ID: 3f9ab99e65c6
Revises: 77bfc5b85f15
Create Date: 2025-08-11 11:10:44.402486

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f9ab99e65c6"
down_revision = "77bfc5b85f15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(), nullable=False))
        batch_op.create_index(batch_op.f("ix_people_location"), ["location"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_people_location"))
        batch_op.drop_column("location")

    # ### end Alembic commands ###
