"""add email address to person

Revision ID: 406c32c0efc8
Revises: e12fcb051874
Create Date: 2026-05-05 13:06:39.880381

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "406c32c0efc8"
down_revision = "e12fcb051874"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_address", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_people_email_address"), ["email_address"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_people_email_address"))
        batch_op.drop_column("email_address")

    # ### end Alembic commands ###
