"""add grade

Revision ID: 77bfc5b85f15
Revises: 94073a373b77
Create Date: 2025-08-06 19:45:28.641156

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "77bfc5b85f15"
down_revision = "94073a373b77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grade", sa.String(), nullable=False))
        batch_op.create_index(batch_op.f("ix_roles_grade"), ["grade"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_grade"))
        batch_op.drop_column("grade")

    # ### end Alembic commands ###
