"""initial migration

Revision ID: b606d20bccfa
Revises:
Create Date: 2025-08-03 19:32:28.519977

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b606d20bccfa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "components",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("components", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_components_name"), ["name"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=True)

    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_name"), ["name"], unique=True)

    op.create_table(
        "people",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_people_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_people_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_people_team_id"), ["team_id"], unique=False)

    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_services_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_services_team_id"), ["team_id"], unique=False)

    op.create_table(
        "service_components",
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "component_id"),
    )
    with op.batch_alter_table("service_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_components_component_id"),
            ["component_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_service_components_service_id"), ["service_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_components_service_id"))
        batch_op.drop_index(batch_op.f("ix_service_components_component_id"))

    op.drop_table("service_components")
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_services_team_id"))
        batch_op.drop_index(batch_op.f("ix_services_name"))

    op.drop_table("services")
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_people_team_id"))
        batch_op.drop_index(batch_op.f("ix_people_role_id"))
        batch_op.drop_index(batch_op.f("ix_people_name"))

    op.drop_table("people")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_name"))

    op.drop_table("teams")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))

    op.drop_table("roles")
    with op.batch_alter_table("components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_components_name"))

    op.drop_table("components")
    # ### end Alembic commands ###
