"""add role profession

Revision ID: c9fff21c75b2
Revises: 8b2d7f1a6c4e
Create Date: 2026-09-09 13:23:04.791170

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9fff21c75b2"
down_revision = "8b2d7f1a6c4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profession", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_roles_profession"), ["profession"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_profession"))
        batch_op.drop_column("profession")

    # ### end Alembic commands ###
