"""add description to service

Revision ID: df48d66eeeaf
Revises: 406c32c0efc8
Create Date: 2026-05-21 10:21:34.902222

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df48d66eeeaf"
down_revision = "406c32c0efc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
