"""add manager and reports

Revision ID: e12fcb051874
Revises: 3f9ab99e65c6
Create Date: 2025-08-24 08:47:35.266401

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e12fcb051874"
down_revision = "3f9ab99e65c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.add_column(sa.Column("manager_id", sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f("ix_people_manager_id"), ["manager_id"], unique=False)
        batch_op.create_foreign_key(None, "people", ["manager_id"], ["id"], ondelete="SET NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_people_manager_id"))
        batch_op.drop_column("manager_id")

    # ### end Alembic commands ###
