name: NodeJS with Webpack

on:
  push:
    branches: ["latest"]
  pull_request:
    branches: ["latest"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Build
        run: |
          cd web
          npm install
          npx webpack
